jobs:
  build:
    name: Build and Upload Artifacts
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout sources
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - continue-on-error: true
      name: Build Artifacts
      uses: gradle/gradle-build-action@v2.4.2
      with:
        arguments: build
    - continue-on-error: true
      name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Artifacts
        path: build/libs/*.jar
name: Upload Artifacts
on:
  repository_dispatch:
    types: trigger-ga___artifacts.yml
